apiVersion: v1
kind: PersistentVolume
metadata:
  name: dws-chatbot-pv
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/dws"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dws-chatbot-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi