apiVersion: v1
kind: PersistentVolume
metadata:
  name: dws-library-db-pv
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/dws-library"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dws-library-db-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi